// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvw6XFlqQUDRwevOr6oag6rvMVjHFGGVo',
    appId: '1:685845837035:web:d3f68e8e41e32b767e7aae',
    messagingSenderId: '685845837035',
    projectId: 'chatapp-13983',
    authDomain: 'chatapp-13983.firebaseapp.com',
    storageBucket: 'chatapp-13983.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXfh9ckoeIps7MNv90AH491zqnLjeH09c',
    appId: '1:685845837035:android:9fe305d78a89f0707e7aae',
    messagingSenderId: '685845837035',
    projectId: 'chatapp-13983',
    storageBucket: 'chatapp-13983.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs2V3q_yOA4MLy6b920jrvTJK6RNPRjbs',
    appId: '1:685845837035:ios:34d45f7265032ce37e7aae',
    messagingSenderId: '685845837035',
    projectId: 'chatapp-13983',
    storageBucket: 'chatapp-13983.appspot.com',
    iosClientId: '685845837035-tu4ns9c2evn99sisqqc808a7nptmk09d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
